### ISSUE TITLE
Exp10: problem with roberta-large-nli-mean-tokens

### ISSUE THREAD

**Issue by MehwishFatimah** [amr-amr/HipoRank#2]
Hi, 
I am trying to reproduce the results on PubMed dataset. I am having the following problem with Roberta model. 

![Screenshot from 2022-03-21 15-43-24](https://user-images.githubusercontent.com/47110754/159285666-a727626d-104e-4b12-be39-b7b9c391c1d1.png)

**Comment by mirandrom** [comment]
Hi Fatimah, what version of sentence-transformers are you using? Can you share with me your modified exp10 code so I can try to replicate it?

**Comment by MehwishFatimah** [comment]
> Hi Fatimah, what version of sentence-transformers are you using? Can you share with me your modified exp10 code so I can try to replicate it?

Thanks for your quick response. I am using sentence-transformers==0.2.5 (same configurations as given). I did not change the code except to add my own paths and some printing statements to understand the flow. In case, if I want to use the Roberta model from disk as like pacsum, would it be possible?

**Comment by mirandrom** [comment]
Hmm, that's strange. I just re-ran exp10 in my environment and didn't have any issues. It's hard to tell from this error message alone since it seems to be something specific to sentence-transformers.

At this point, the simplest option would be to write your own embedder class that implements `get_embeddings`.
That way you can also implement the desired behavior of loading from disk, or use more recent/stable versions of libraries like transformers or sentence-transformers.


If you want to try and fix your current error message, I would first make sure it's not a discrepancy in environments.

You can try the following:
Setup your environment with Python 3.7.
Ensure your dependencies match the entire output of my environment's `pip freeze`:
```
backcall==0.2.0
boto3==1.16.51
botocore==1.19.51
cached-property==1.5.2
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
dataclasses==0.6
decorator==4.4.2
filelock==3.0.12
gensim==3.8.1
h5py==3.2.1
idna==2.10
ipykernel==5.5.0
ipython==7.21.0
ipython-genutils==0.2.0
jedi==0.18.0
jmespath==0.10.0
joblib==1.0.0
jupyter-client==6.1.12
jupyter-core==4.7.1
nltk==3.5
numpy==1.19.5
packaging==20.8
parso==0.8.1
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.18
ptyprocess==0.7.0
py-rouge==1.1
Pygments==2.8.1
pyparsing==2.4.7
pyrouge==0.1.3
python-dateutil==2.8.1
pyzmq==22.0.3
regex==2020.11.13
requests==2.25.1
s3transfer==0.3.3
sacremoses==0.0.43
scikit-learn==0.24.0
scipy==1.6.0
sentence-transformers==0.2.5
sentencepiece==0.1.95
six==1.15.0
smart-open==4.1.0
threadpoolctl==2.1.0
tokenizers==0.9.4
torch==1.3.1
```

**Comment by MehwishFatimah** [comment]
Thank you so much for your detailed reponse. I set up the environment with Python 3.7.0 and other dependencies. Unfortunately, it could not resolve Roberta issue. As far as I understood, the problem is in Sentence Transformer definitions which could not detect Roberta.
